config/routes.rb
Rails.application.routes.draw do
	root 'posts#index'

	resources 'posts'
	resources 'users'

	get    '/login',  to: 'sessions#new'
	post   '/login',  to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, 
					  presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :email, presence: true, uniqueness: true
	validates :password, length: { minimum:5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :logged_in_user, only: [:new, :create]

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.author = current_user.email
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end	
	end

	def destroy
		Post.find(params[:id]).destroy
		redirect_to posts_url
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end

	def logged_in_user
		unless logged_in?
			flash[:danger] = "You must be logged in to create a post"
			redirect_to root_url
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])
  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
  		redirect_to user
  	else
  		flash.now[:danger] = "Invalid email or password"	
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to posts_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		@title = 'About Us'
		@content = 'This is the content'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	private

	def user_params
		params.require(:user).permit(:email,:password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def correct_user(email)
		email == @current_user.email
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to "Members Only", posts_path %></h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <%= link_to "All Posts", posts_path  %>
      </nav>
      <% if logged_in? %>
        <nav class="my-2 my-md-0 mr-md-3">
          <%= link_to "New Post", new_post_path %>
        </nav>
        <%= link_to "Log out", logout_path, method: :delete %> 
      <% else %>
        <%= link_to "Log in", login_path %>
      <% end %> 
    </div>
    <div class="container">
      <% flash.each do |msg_type, msg| %>
        <p><%= msg %><p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %> 

 <% if @post.errors.any? %>
 	<% @post.errors.full_messages.each do |msg| %>
 		<div class='alert alert-danger'><%= msg %> </div>
	<% end %>
 <% end %> 

	<p>
		<%= f.label 		 :title %> <br>
		<%= f.text_field :title, class: 'form-control' %>
	</p>	

	<p>
		<%= f.label 		:body %> <br>
		<%= f.text_area :body, class: 'form-control' %> 
	</p>

	<p>
		<%= f.submit "Save post", class: 'btn btn-primary' %>
	</p>
<% end %> 

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
	<div class='well'>
		<h3><%= post.title %></h3>
		<p><%= post.body %></p>
		<%= link_to "Read More", post_path(post), class: "btn btn-default"	 %>
	</div>
<% end %> 

app/views/posts/new.html.erb
<h1>Add Post</h1>

<%= form_for :post, url: posts_path do |f| %> 

 <% if @post.errors.any? %>
 	<% @post.errors.full_messages.each do |msg| %>
 		<div class='alert alert-danger'><%= msg %> </div>
	<% end %>
 <% end %> 

	<p>
		<%= f.label 		 :title %> <br>
		<%= f.text_field :title, class: 'form-control' %>
	</p>	

	<p>
		<%= f.label 		:body %> <br>
		<%= f.text_area :body, class: 'form-control' %> 
	</p>

	<p>
		<%= f.submit "Save post", class: 'btn btn-primary' %>
	</p>
<% end %> 

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p> <%= @post.body %></p>
<hr>
<% if logged_in? %> 
	<p><%= @post.author %></p>
<% end %> 

<% if logged_in? && correct_user(@post.author) %> 
	<%= link_to "Edit", edit_post_path(@post), class: 'btn btn-default' %>
	<%= link_to "Delete", post_path(@post), method: :delete,
																					data: {confirm: "Are you sure?"},		
																					class: 'btn btn-danger' %>
<% end %> 

app/views/static_pages/home.html.erb
<h1><%= @title %></h1>
<p> <%= @content %> </p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for :user, url: users_path do |f| %> 

	<%if @user.errors.any? %>
		<%@user.errors.full_messages.each do | error | %> 
			<p class='error'><%= error %></p>
		<% end %>
	<% end %>
	<p>
		<%= f.label 		 :email %> <br>
		<%= f.text_field :email, class: 'form-control' %>
	</p>	

	<p>
		<%= f.label 			   :password %> <br>
		<%= f.password_field :password, class: 'form-control' %> 
	</p>

	<p>
		<%= f.label 				 :password_confirmation %> <br>
		<%= f.password_field :password_confirmation, class: 'form-control' %> 
	</p>

	<p>
		<%= f.submit "Sign up", class: 'btn btn-primary' %>
	</p>
<% end %> 

app/views/users/show.html.erb
<h1>Profile</h1>

<p><%= @user.email %></p>